language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/native-blink
  - PLATFORMIO_PROJECT_DIR=examples/spl-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-fade-all-pins

install:
  - pip install platformio
    pio update
  - pio platform install file://.

script:
  - qio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
